### ISSUE TITLE
module load e3sm-unified broken on theta

### ISSUE THREAD

**Issue by PeterCaldwell** [E3SM-Project/e3sm-unified#15]
The e3sm-unified modules on theta seems to be screwed up now. They try to point to paths of the form /projects/ClimateEnergy_2/software/e3sm_unified/e3sm_unified_1.1.X_py2_nox/bin but now only /projects/ClimateEnergy_2/software/e3sm_unified/ exists and it only has a subdirectory called "base".

**Comment by xylar** [comment]
@PeterCaldwell, sorry about that.  I was not aware that these older versions of e3sm-unified were in use on theta.  Could you see if you can change to using e3sm-unified 1.2.0 on Theta?  See the Software and Supported Machines Confluence page for details.  If that doesn't work for you, I can attempt to re-create the older environments.

We had an issue where the current e3sm-unified could not be used from Cooley and needed to be rebuilt.  We have been told not to run analysis on Theta login nodes and we cannot do so on Theta compute nodes because of the requirement for high node count.  So I was rebuilding the e3sm-unified environment for cross-compatibility with Cooley.  Because of changes in conda itself, it is difficult to create environments in the existing path and not possible to use module files as had been the case for older e3sm-unified versions.

**Comment by xylar** [comment]
@PeterCaldwell, following up on our phone call, I was actually able to move the old versions back in place.  I tested them out and they work fine.  They won't work on Cooley but that's not a problem.

Sorry for the confusion and hassle.

**Comment by xylar** [comment]
I'll close this for now but please re-open if you have trouble.

**Comment by milenaveneziani** [comment]
As FYI, since I ran into trouble running diagnostics on the high-res using the theta login node, I am in the process of changing a-prime so that we only use cooley at ALCF for running diagnostics. I have also included a batch job for running a-prime on cooley's compute nodes. Pinging @chengzhuzhang here as well, since I suppose this will be a general diagnostics problem at ALCF.

**Comment by PeterCaldwell** [comment]
Hi Milena - to be clear, when you say "ran into trouble", you mean that ALCF folks got mad at you, right? I'm not implying you're doing anything wrong, I'm trying to figure out whether I can expect an angry call myself ;-)

**Comment by milenaveneziani** [comment]
yes, they got mad at me :) I was told to either use the debug queue or cooley. The debug queue doesn't work for us because it's only for 1 hour, and we can easily go over that with the high-res..

**Comment by maltrud** [comment]
@PeterCaldwell , i also got a cease email from the ALCF weenies several months ago when running ncremap.  the problem was that nco defaults to using /tmp for scratch files and if ncremap gags the large files stay there.  probably best to move to cooley for everything.

**Comment by PeterCaldwell** [comment]
I thought theta scratch disks weren't available on Cooley though. Has that changed, or are you moving the data from theta -> cooley before analyzing it? The latter situation would be a bummer.

**Comment by maltrud** [comment]
@PeterCaldwell , yes it has changed and the project space on theta is now visible on cooley.  before, i had to transfer files via hpss.

**Comment by PeterCaldwell** [comment]
Great, I'm glad that changed. Thanks Mat.

**Comment by milenaveneziani** [comment]
yes, @PeterCaldwell. The full path to the ClimateEnergy_2 project space, which works on any machine, is: `/lus/theta-fs0/projects/ClimateEnergy_2`.
